### ISSUE TITLE
GPL-532 BUG - wrong file breaks crawler process

### ISSUE THREAD

**Issue by emrojo** [sanger/crawler#39]
**Describe the bug**
A file with wrong data can break all crawler process from a center. We need to provide a method to exclude certain files from being processed when we found they have a problem or are not right.

**RT Ticket Number**
Error on Jun 11th

**To Reproduce**
Steps to reproduce the behaviour:
1. Upload a file without header
2. It fails with following output:
```
2020-06-11 11:34:23,190 crawler.main    :101 INFO    ********************************************************************************
2020-06-11 11:34:23,190 crawler.main    :102 INFO    Processing xxxxx
2020-06-11 11:34:23,711 crawler.helpers :147 INFO    Downloading CSV files...
2020-06-11 11:34:27,618 crawler.helpers :268 INFO    Merging daily files of xxxxx
2020-06-11 11:34:27,619 crawler.helpers :272 INFO    59 files to merge into master file
2020-06-11 11:34:37,357 crawler.main    :139 ERROR   dict contains fields not in fieldnames:....
Traceback (most recent call last):
  File "/code/crawler/main.py", line 112, in run
    master_file_name = merge_daily_files(config, centre)
  File "/code/crawler/helpers.py", line 321, in merge_daily_files
    writer.writerow(row)
  File "/usr/local/lib/python3.8/csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "/usr/local/lib/python3.8/csv.py", line 149, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in .....
2020-06-11 11:34:38,633 crawler.main    :143 INFO    0 documents inserted
2020-06-11 11:34:38,634 crawler.main    :101 INFO    ********************************************************************************
```

**Expected behaviour**
* File is ignored if it is set in a black list.
* A wrong file is ignored from process, but does not break all load

**Additional context**

**Comment by emrojo** [comment]
Check what has been received today in AssetAudits and if it hasnt created in Sequencescape because of Lighthouse trigger again the reception of labware.

**Comment by rl15** [comment]
Just for the record;

MK uploaded two plate map files for the same day on the 10th June to SFTP.
 
MK_sanger_report_200610_0001 – Misplaced header (is at row 512) , Missing data for RNA ID, RNA-PCR ID and just 525 samples.  Note hhmm timestamp what we typically see; ie 0001
MK_sanger_report_200610_2000 – Defacto standard file, ~25k samples however hhmm timestamp is unusual

Cristina A raising with MK. -
