### ISSUE TITLE
GPL-575 BUG - error on job process - lighthouse crawler

### ISSUE THREAD

**Issue by emrojo** [sanger/crawler#64]
**Describe the bug**
This is part of the log from the error:

```
Traceback (most recent call last):
  File "/code/crawler/main.py", line 147, in run
    raise CollectionError
  File "/usr/local/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/code/crawler/db.py", line 159, in safe_collection
    rename_collection_with_suffix(original_collection, timestamp)
  File "/code/crawler/db.py", line 103, in rename_collection_with_suffix
    rename_collection(collection, new_name)
  File "/code/crawler/db.py", line 117, in rename_collection
    collection.rename(new_name)
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 2613, in rename
    return sock_info.command(
  File "/usr/local/lib/python3.8/site-packages/pymongo/pool.py", line 603, in command
    return command(self.sock, dbname, spec, slave_ok,
  File "/usr/local/lib/python3.8/site-packages/pymongo/network.py", line 165, in command
    helpers._check_command_response(
  File "/usr/local/lib/python3.8/site-packages/pymongo/helpers.py", line 159, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: target namespace exists
```
**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by emrojo** [comment]
To create a test that starts several instances of mongodb in local that work in a replicated set:
 
```bash
MONGO_PORTS=(21234 21235 21236 21237 21238)
REPLICA=rstest0
for PORT in ${MONGO_PORTS[@]}; do
  MONGO_PATH=/tmp/mongodb$PORT
  mkdir $MONGO_PATH

  cat >$MONGO_PATH/mongod.conf <<EOF
net:
  bindIp: 127.0.0.1
storage:
  dbPath: $MONGO_PATH
EOF
  mongod -f $MONGO_PATH/mongod.conf --port $PORT --replSet rstest0 &
done

FIRST_PORT=${MONGO_PORTS[0]}

for PORT in ${MONGO_PORTS[@]}; do
  if [[ $PORT -eq $FIRST_PORT ]]; then
    mongo mongodb://localhost:$FIRST_PORT --eval "rs.initiate()"
  else
    mongo mongodb://localhost:$FIRST_PORT --eval "rs.add('localhost:$PORT')"
  fi
done
```

**Comment by emrojo** [comment]
Cannot reproduce it. It doesnt happen if we run it manually, or in uat. Seems it only happened during scheduled run. I've restarted the service and will check tomorrow.

I thought it could be in this line:
```
def run(sftp: bool, settings_module: str = "", timestamp: str = current_time()) -> None:
```
this job is delayed, but I'm not sure current_time() will be re-evaluated every trigger. That could explain why collections can't be renamed, if the new name already exists. But then, why it doesn't happen in UAT?

**Comment by emrojo** [comment]
It didnt happen today. Could it be an out of date container was deployed? 
I'll leave closed unless it happens again
